swagger: '2.0'
info:
  version: '1.0'
  title: "ecomma"
  description: A simple API for simple e-commerce stuff.
  license:
    name: GPL3
    url: https://github.com/carlvelde/ecomma/blob/master/LICENSE
host: ecomma.apiblueprint.org
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /stock/findByVariant:
    x-summary: Stock levels
    get:
      summary: Get stock levels for one or more variants. Optional to filter by warehouse.
      produces:
      - "application/json"
      parameters:
      - name: "warehouseId"
        in: "query"
        description: "Warehouse id to filter out stock for a specific warehouse"
        required: false
        type: "string"
      - name: "variantId"
        in: "query"
        description: "One or more Variant ids to get by"
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/VariantStockLevel'
          
definitions:
  VariantStockLevel:
    title: StockStaus
    type: object
    properties:
      variant_id:
        type: string
      warehouse_code:
        type: string
      updated:
        type: string
        format: date-time
      stock_level:
        type: integer
    required:
      - variant_id
      - warehouse_code
      - updated
      - stock_level